import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import crmRouter from "./crm";
import ticketsRouter from "./tickets";
import hrRouter from "./hr";
import financeRouter from "./finance";
import fieldServiceRouter from "./field-service";
import omnichannelRouter from "./omnichannel";
import aiRouter from "./ai";
import gamificationRouter from "./gamification";
import automationsRouter from "./automations";
import stripeRouter from "./stripe";
import contractsRouter from "./contracts";
import customerSuccessRouter from "./customer-success";
import businessHealthRouter from "./business-health";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(dashboardRouter);
router.use(businessHealthRouter);
router.use(contractsRouter);
router.use(customerSuccessRouter);
router.use(crmRouter);
router.use(ticketsRouter);
router.use(hrRouter);
router.use(financeRouter);
router.use(fieldServiceRouter);
router.use(omnichannelRouter);
router.use(aiRouter);
router.use(gamificationRouter);
router.use(automationsRouter);
router.use(stripeRouter);
router.use(adminRouter);

export default router;
